name: Build & Deploy Loopara Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build Docker image and deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: michaelgirardet/loopara-frontend:latest

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            docker stop loopara || true
            docker rm loopara || true
            docker pull michaelgirardet/loopara-frontend:latest
            docker run -d --name loopara -p 3001:80 michaelgirardet/loopara-frontend:latest
